//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.Client.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.Client.Core.Resources.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_About {
            get {
                return ResourceManager.GetString("About_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string About_Privacy {
            get {
                return ResourceManager.GetString("About_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string About_TermsAndConditions {
            get {
                return ResourceManager.GetString("About_TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully accepted the invitation, but will remain logged in with the organization you are currently assocaited with.  To switch to this new organization, click on the Organization Link on the new menu.
        /// </summary>
        public static string Accept_AcceptLoggedInSuccessful {
            get {
                return ResourceManager.GetString("Accept_AcceptLoggedInSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string AcceptInvite_Accept {
            get {
                return ResourceManager.GetString("AcceptInvite_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you are already logged in, you can simply accept the invitation, you will not automatically be switched to that organization however..
        /// </summary>
        public static string AcceptInvite_Accept_Help {
            get {
                return ResourceManager.GetString("AcceptInvite_Accept_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept and Login.
        /// </summary>
        public static string AcceptInvite_AcceptAndLogin {
            get {
                return ResourceManager.GetString("AcceptInvite_AcceptAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you already have an account, you can simply accept the invitation and login..
        /// </summary>
        public static string AcceptInvite_AcceptAndLogin_Help {
            get {
                return ResourceManager.GetString("AcceptInvite_AcceptAndLogin_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept and Register.
        /// </summary>
        public static string AcceptInvite_AcceptAndRegister {
            get {
                return ResourceManager.GetString("AcceptInvite_AcceptAndRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you accept the registration, you will be prompted to create a user account..
        /// </summary>
        public static string AcceptInvite_AcceptAndRegister_Help {
            get {
                return ResourceManager.GetString("AcceptInvite_AcceptAndRegister_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Invitation.
        /// </summary>
        public static string AcceptInvite_Title {
            get {
                return ResourceManager.GetString("AcceptInvite_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we could not validate the Email Address and Password you supplied..
        /// </summary>
        public static string Auth_FailedLogin {
            get {
                return ResourceManager.GetString("Auth_FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has been Changed.
        /// </summary>
        public static string ChangePassword_Confirmed {
            get {
                return ResourceManager.GetString("ChangePassword_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ChangePassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -confirm your new password-.
        /// </summary>
        public static string ChangePassword_ConfirmNewPassword_WaterMark {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmNewPassword_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is a Required Field.
        /// </summary>
        public static string ChangePassword_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your New Password and Confrim Password Must Match.
        /// </summary>
        public static string ChangePassword_NewConfirmMatch {
            get {
                return ResourceManager.GetString("ChangePassword_NewConfirmMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ChangePassword_NewPassword {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter a new password-.
        /// </summary>
        public static string ChangePassword_NewPassword_WaterMark {
            get {
                return ResourceManager.GetString("ChangePassword_NewPassword_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is a Required Field.
        /// </summary>
        public static string ChangePassword_NewPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePassword_NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string ChangePassword_OldPassword {
            get {
                return ResourceManager.GetString("ChangePassword_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter your old password-.
        /// </summary>
        public static string ChangePassword_OldPassword_WaterMark {
            get {
                return ResourceManager.GetString("ChangePassword_OldPassword_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is a Required Field.
        /// </summary>
        public static string ChangePassword_OldPasswordRequired {
            get {
                return ResourceManager.GetString("ChangePassword_OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has successfully been changed..
        /// </summary>
        public static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your Password.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Common_Email_Password {
            get {
                return ResourceManager.GetString("Common_Email_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string Common_Email_Watermark {
            get {
                return ResourceManager.GetString("Common_Email_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Common_EmailAddress {
            get {
                return ResourceManager.GetString("Common_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error communicating with the server.   Please try again later..
        /// </summary>
        public static string Common_ErrorCommunicatingWithServer {
            get {
                return ResourceManager.GetString("Common_ErrorCommunicatingWithServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Common_GetStarted {
            get {
                return ResourceManager.GetString("Common_GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Key is already in use, please select a different Key..
        /// </summary>
        public static string Common_KeyInUse {
            get {
                return ResourceManager.GetString("Common_KeyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Common_Login {
            get {
                return ResourceManager.GetString("Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Common_Logout {
            get {
                return ResourceManager.GetString("Common_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There does not appear to be a connection to the internet, please check your connectoin and try again .ater..
        /// </summary>
        public static string Common_NoConnection {
            get {
                return ResourceManager.GetString("Common_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Common_Submit {
            get {
                return ResourceManager.GetString("Common_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.  Are you sure you want to exit?.
        /// </summary>
        public static string Confirm_Unsaved_Message {
            get {
                return ResourceManager.GetString("Confirm_Unsaved_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Confirm_Unsaved_Title {
            get {
                return ResourceManager.GetString("Confirm_Unsaved_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?  This can not be undone!.
        /// </summary>
        public static string ConfirmDelete_Msg {
            get {
                return ResourceManager.GetString("ConfirmDelete_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        public static string ConfirmDelete_Title {
            get {
                return ResourceManager.GetString("ConfirmDelete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Organization.
        /// </summary>
        public static string CurrentOrganization_Label {
            get {
                return ResourceManager.GetString("CurrentOrganization_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor Console Output.
        /// </summary>
        public static string DeviceMore_Console {
            get {
                return ResourceManager.GetString("DeviceMore_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update.
        /// </summary>
        public static string DeviceMore_FirmwareUpdate {
            get {
                return ResourceManager.GetString("DeviceMore_FirmwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O Configuration.
        /// </summary>
        public static string DeviceMore_IOConfig {
            get {
                return ResourceManager.GetString("DeviceMore_IOConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Data.
        /// </summary>
        public static string DeviceMore_LiveData {
            get {
                return ResourceManager.GetString("DeviceMore_LiveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pair Device.
        /// </summary>
        public static string DeviceMore_PairDevice {
            get {
                return ResourceManager.GetString("DeviceMore_PairDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision.
        /// </summary>
        public static string DeviceMore_Provision {
            get {
                return ResourceManager.GetString("DeviceMore_Provision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device repositories.
        /// </summary>
        public static string DeviceReposView_NoDeviceRepos {
            get {
                return ResourceManager.GetString("DeviceReposView_NoDeviceRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Respositories.
        /// </summary>
        public static string DeviceReposView_Title {
            get {
                return ResourceManager.GetString("DeviceReposView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Serial Port Access.
        /// </summary>
        public static string DeviceSerialPort_View {
            get {
                return ResourceManager.GetString("DeviceSerialPort_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices.
        /// </summary>
        public static string DevicesView_NoDevice {
            get {
                return ResourceManager.GetString("DevicesView_NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -search devices by id-.
        /// </summary>
        public static string DevicesView_SearchWatermark {
            get {
                return ResourceManager.GetString("DevicesView_SearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -select device type-.
        /// </summary>
        public static string DevicesView_SelectDeviceType {
            get {
                return ResourceManager.GetString("DevicesView_SelectDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string DevicesView_Title {
            get {
                return ResourceManager.GetString("DevicesView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string DeviceView_Attributes {
            get {
                return ResourceManager.GetString("DeviceView_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        public static string DeviceView_DeviceId {
            get {
                return ResourceManager.GetString("DeviceView_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Contact.
        /// </summary>
        public static string DeviceView_LastContact {
            get {
                return ResourceManager.GetString("DeviceView_LastContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string DeviceView_Messages {
            get {
                return ResourceManager.GetString("DeviceView_Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string DeviceView_Name {
            get {
                return ResourceManager.GetString("DeviceView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string DeviceView_Send {
            get {
                return ResourceManager.GetString("DeviceView_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machines.
        /// </summary>
        public static string DeviceView_StateMachines {
            get {
                return ResourceManager.GetString("DeviceView_StateMachines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string DeviceView_Status {
            get {
                return ResourceManager.GetString("DeviceView_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device View.
        /// </summary>
        public static string DeviceView_Title {
            get {
                return ResourceManager.GetString("DeviceView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device.
        /// </summary>
        public static string EditDevice_Title {
            get {
                return ResourceManager.GetString("EditDevice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call was not completed..
        /// </summary>
        public static string Err_CallNotCompleted {
            get {
                return ResourceManager.GetString("Err_CallNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not renew access token, please check server and mobile logs.
        /// </summary>
        public static string Err_CouldNotRenewToken {
            get {
                return ResourceManager.GetString("Err_CouldNotRenewToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error calling the server. Please try again later..
        /// </summary>
        public static string Err_GeneralErrorCallingServer {
            get {
                return ResourceManager.GetString("Err_GeneralErrorCallingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string Err_NotAuthorized {
            get {
                return ResourceManager.GetString("Err_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not connected to the internet..
        /// </summary>
        public static string Err_NotConnected {
            get {
                return ResourceManager.GetString("Err_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have been logged out.  Please login again..
        /// </summary>
        public static string Err_PleaseLoginAgain {
            get {
                return ResourceManager.GetString("Err_PleaseLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Error.
        /// </summary>
        public static string Err_TokenError {
            get {
                return ResourceManager.GetString("Err_TokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string InviteUser_Email {
            get {
                return ResourceManager.GetString("InviteUser_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -send invitation to email-.
        /// </summary>
        public static string InviteUser_Email_Watermark {
            get {
                return ResourceManager.GetString("InviteUser_Email_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an Invitation to some one to join the [ORGNAME] organization.  They will be prompted to create a new user if they don&apos;t already have one, or will be added to your organization if they do..
        /// </summary>
        public static string InviteUser_Help {
            get {
                return ResourceManager.GetString("InviteUser_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Invitation has been sent to the user, once they receive it, they can either login with their current account or register as a new user..
        /// </summary>
        public static string InviteUser_InvitationSent {
            get {
                return ResourceManager.GetString("InviteUser_InvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Message.
        /// </summary>
        public static string InviteUser_Message {
            get {
                return ResourceManager.GetString("InviteUser_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -add a message to the invitation-.
        /// </summary>
        public static string InviteUser_Message_Watermark {
            get {
                return ResourceManager.GetString("InviteUser_Message_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string InviteUser_Name {
            get {
                return ResourceManager.GetString("InviteUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -name of individual to invite-.
        /// </summary>
        public static string InviteUser_Name_Watermark {
            get {
                return ResourceManager.GetString("InviteUser_Name_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite User.
        /// </summary>
        public static string InviteUser_Submit {
            get {
                return ResourceManager.GetString("InviteUser_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite a New User.
        /// </summary>
        public static string InviteUser_Title {
            get {
                return ResourceManager.GetString("InviteUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainMenu_About {
            get {
                return ResourceManager.GetString("MainMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string MainMenu_ChangePassword {
            get {
                return ResourceManager.GetString("MainMenu_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite User.
        /// </summary>
        public static string MainMenu_InviteUser {
            get {
                return ResourceManager.GetString("MainMenu_InviteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Organization.
        /// </summary>
        public static string MainMenu_NoOrganization {
            get {
                return ResourceManager.GetString("MainMenu_NoOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Organization.
        /// </summary>
        public static string MainMenu_SwitchOrgs {
            get {
                return ResourceManager.GetString("MainMenu_SwitchOrgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -select input command-.
        /// </summary>
        public static string MonitorDevice_SelectInputCommand {
            get {
                return ResourceManager.GetString("MonitorDevice_SelectInputCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Editor.
        /// </summary>
        public static string OrgEditor_Title {
            get {
                return ResourceManager.GetString("OrgEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must contain at least 8 characters, with at least one number and one upper case and one lower case letter.
        /// </summary>
        public static string Password_Requirements {
            get {
                return ResourceManager.GetString("Password_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provision Device.
        /// </summary>
        public static string Provions_Title {
            get {
                return ResourceManager.GetString("Provions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem Baud Rate.
        /// </summary>
        public static string Provision_BaudRate {
            get {
                return ResourceManager.GetString("Provision_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular Connection Enabled.
        /// </summary>
        public static string Provision_CellEnabled {
            get {
                return ResourceManager.GetString("Provision_CellEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission.
        /// </summary>
        public static string Provision_Commission {
            get {
                return ResourceManager.GetString("Provision_Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id.
        /// </summary>
        public static string Provision_DeviceId {
            get {
                return ResourceManager.GetString("Provision_DeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        public static string Provision_DeviceType {
            get {
                return ResourceManager.GetString("Provision_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware SKU.
        /// </summary>
        public static string Provision_Firmware_SKU {
            get {
                return ResourceManager.GetString("Provision_Firmware_SKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        public static string Provision_Firmware_Version {
            get {
                return ResourceManager.GetString("Provision_Firmware_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Enabled.
        /// </summary>
        public static string Provision_GPSEnabled {
            get {
                return ResourceManager.GetString("Provision_GPSEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Update Rate.
        /// </summary>
        public static string Provision_GPSUpdateRate {
            get {
                return ResourceManager.GetString("Provision_GPSUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardawre Version.
        /// </summary>
        public static string Provision_Hardware_Version {
            get {
                return ResourceManager.GetString("Provision_Hardware_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Update Rate.
        /// </summary>
        public static string Provision_PingUpdateRate {
            get {
                return ResourceManager.GetString("Provision_PingUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string Provision_Reboot {
            get {
                return ResourceManager.GetString("Provision_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Profile.
        /// </summary>
        public static string Provision_ResetProfile {
            get {
                return ResourceManager.GetString("Provision_ResetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Anonymous Connection.
        /// </summary>
        public static string Provision_Server_Anonymous {
            get {
                return ResourceManager.GetString("Provision_Server_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Host Name.
        /// </summary>
        public static string Provision_Server_Host {
            get {
                return ResourceManager.GetString("Provision_Server_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Password.
        /// </summary>
        public static string Provision_Server_Password {
            get {
                return ResourceManager.GetString("Provision_Server_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server User Id.
        /// </summary>
        public static string Provision_Server_UserId {
            get {
                return ResourceManager.GetString("Provision_Server_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Update Rate.
        /// </summary>
        public static string Provision_SrvrUpdateRate {
            get {
                return ResourceManager.GetString("Provision_SrvrUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose Logging.
        /// </summary>
        public static string Provision_VerboseLogging {
            get {
                return ResourceManager.GetString("Provision_VerboseLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Password.
        /// </summary>
        public static string Provision_WiFi_Password {
            get {
                return ResourceManager.GetString("Provision_WiFi_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi SSID.
        /// </summary>
        public static string Provision_WiFi_SSID {
            get {
                return ResourceManager.GetString("Provision_WiFi_SSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Connection Enabled.
        /// </summary>
        public static string Provision_WiFiEnabled {
            get {
                return ResourceManager.GetString("Provision_WiFiEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Profile.
        /// </summary>
        public static string Provision_WriteProfile {
            get {
                return ResourceManager.GetString("Provision_WriteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Register_Confirm_Password {
            get {
                return ResourceManager.GetString("Register_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your new password.
        /// </summary>
        public static string Register_ConfirmPassword_Watermark {
            get {
                return ResourceManager.GetString("Register_ConfirmPassword_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Register_Email {
            get {
                return ResourceManager.GetString("Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string Register_Email_Invalid {
            get {
                return ResourceManager.GetString("Register_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is a Required FIeld.
        /// </summary>
        public static string Register_Email_Required {
            get {
                return ResourceManager.GetString("Register_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string Register_Email_WaterMark {
            get {
                return ResourceManager.GetString("Register_Email_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Register_FirstName {
            get {
                return ResourceManager.GetString("Register_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is a Required Field.
        /// </summary>
        public static string Register_FirstName_Required {
            get {
                return ResourceManager.GetString("Register_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        public static string Register_FirstName_WaterMark {
            get {
                return ResourceManager.GetString("Register_FirstName_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Register_LastName {
            get {
                return ResourceManager.GetString("Register_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is a Required Field.
        /// </summary>
        public static string Register_LastName_Required {
            get {
                return ResourceManager.GetString("Register_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        public static string Register_LastName_WaterMark {
            get {
                return ResourceManager.GetString("Register_LastName_WaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password must match..
        /// </summary>
        public static string Register_Password_Confirm_NoMatch {
            get {
                return ResourceManager.GetString("Register_Password_Confirm_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is a Required Field.
        /// </summary>
        public static string Register_Password_Required {
            get {
                return ResourceManager.GetString("Register_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a password.
        /// </summary>
        public static string Register_Password_Watermark {
            get {
                return ResourceManager.GetString("Register_Password_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ResetPassword_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ResetPassword_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your new password.
        /// </summary>
        public static string ResetPassword_ConfirmNewPassword_Watermark {
            get {
                return ResourceManager.GetString("ResetPassword_ConfirmNewPassword_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ResetPassword_NewPassword {
            get {
                return ResourceManager.GetString("ResetPassword_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -enter a new password-.
        /// </summary>
        public static string ResetPassword_NewPassword_Watermark {
            get {
                return ResourceManager.GetString("ResetPassword_NewPassword_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword_Submit {
            get {
                return ResourceManager.GetString("ResetPassword_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password has Successfully been Reset, you can now log into the system with your email address and new password..
        /// </summary>
        public static string ResetPassword_SuccessMessage {
            get {
                return ResourceManager.GetString("ResetPassword_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your Password.
        /// </summary>
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string SendResetPasswordLink_Email {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string SendResetPasswordLink_Email_Watermark {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Email_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the email address you used to create your NuvIoT account and press Send Link. You will receive an email with a link that will allow you to reset your password..
        /// </summary>
        public static string SendResetPasswordLink_Help {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your email account is in the system, you will be sent a message with a link you can use to reset your password. If you do not receive a Password Reset Email within 5 minutes, please check your junk or other folder..
        /// </summary>
        public static string SendResetPasswordLink_Message {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your Password.
        /// </summary>
        public static string SendResetPasswordLink_Title {
            get {
                return ResourceManager.GetString("SendResetPasswordLink_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Link.
        /// </summary>
        public static string SendRestPasswordLink_Send {
            get {
                return ResourceManager.GetString("SendRestPasswordLink_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Organization.
        /// </summary>
        public static string UserOrgs_Title {
            get {
                return ResourceManager.GetString("UserOrgs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string UserOrgs_WelcometoNew {
            get {
                return ResourceManager.GetString("UserOrgs_WelcometoNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Code.
        /// </summary>
        public static string Verify_ConfirmCode {
            get {
                return ResourceManager.GetString("Verify_ConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your email address has been confirmed..
        /// </summary>
        public static string Verify_Email_Confirmed {
            get {
                return ResourceManager.GetString("Verify_Email_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email message has been sent and should arrive in your inbox shortly.  If you do not receive it in a few minutes, please check other folders where it may been routed..
        /// </summary>
        public static string Verify_EmailSent {
            get {
                return ResourceManager.GetString("Verify_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Verify_PhoneNumber {
            get {
                return ResourceManager.GetString("Verify_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number.
        /// </summary>
        public static string Verify_PhoneNumber_Watermark {
            get {
                return ResourceManager.GetString("Verify_PhoneNumber_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recevied Code.
        /// </summary>
        public static string Verify_ReceivedCode {
            get {
                return ResourceManager.GetString("Verify_ReceivedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 5 or 6 digit code.
        /// </summary>
        public static string Verify_ReceivedCode_Watermark {
            get {
                return ResourceManager.GetString("Verify_ReceivedCode_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Confirmation Email.
        /// </summary>
        public static string Verify_SendEmail {
            get {
                return ResourceManager.GetString("Verify_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send SMS Confirmation.
        /// </summary>
        public static string Verify_SendSMS {
            get {
                return ResourceManager.GetString("Verify_SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Step.
        /// </summary>
        public static string Verify_SkipStep {
            get {
                return ResourceManager.GetString("Verify_SkipStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your phone number has been confirmed..
        /// </summary>
        public static string Verify_SMS_Confirmed {
            get {
                return ResourceManager.GetString("Verify_SMS_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SMS message has been sent, please check your phone and enter the code you receive..
        /// </summary>
        public static string Verify_SMSSent {
            get {
                return ResourceManager.GetString("Verify_SMSSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your Identity.
        /// </summary>
        public static string Verify_Title {
            get {
                return ResourceManager.GetString("Verify_Title", resourceCulture);
            }
        }
    }
}
